sed -i 's/getTunerIdLabel().setText(getTuner().getPreferredName());/getTunerIdLabel().setText(getTuner().getPreferredName() + getUsbInfo());/g' ./src/main/java/io/github/dsheirer/source/tuner/airspy/AirspyTunerEditor.java
sed -i 's/getTunerIdLabel().setText("Airspy " + getTuner().getController().getBoardId() + " SER# " +/getTunerIdLabel().setText("Airspy " + getTuner().getController().getBoardId() + " SER# " + getTuner().getController().getSerialNumber() + getUsbInfo()); \/\//g' ./src/main/java/io/github/dsheirer/source/tuner/airspy/hf/AirspyHfTunerEditor.java
sed -i 's/getTunerIdLabel().setText("Airspy HF+");/getTunerIdLabel().setText("Airspy HF+" + getUsbInfo());/g' ./src/main/java/io/github/dsheirer/source/tuner/airspy/hf/AirspyHfTunerEditor.java
sed -i 's/getTunerIdLabel().setText(getTuner().getPreferredName());/getTunerIdLabel().setText(getTuner().getPreferredName() + getUsbInfo());/g' ./src/main/java/io/github/dsheirer/source/tuner/hackrf/HackRFTunerEditor.java
sed -i 's/getTunerIdLabel().setText(getTuner().getPreferredName());/getTunerIdLabel().setText(getTuner().getPreferredName() + getUsbInfo());/g' ./src/main/java/io/github/dsheirer/source/tuner/recording/RecordingTunerEditor.java
sed -i 's/getTunerIdLabel().setText(getTuner().getPreferredName());/getTunerIdLabel().setText(getTuner().getPreferredName() + getUsbInfo());/g' ./src/main/java/io/github/dsheirer/source/tuner/fcd/proplusV2/FCD2TunerEditor.java
sed -i 's/getTunerIdLabel().setText(getTuner().getPreferredName());/getTunerIdLabel().setText(getTuner().getPreferredName() + getUsbInfo());/g' ./src/main/java/io/github/dsheirer/source/tuner/fcd/proV1/FCD1TunerEditor.java
sed -i 's/getTunerIdLabel().setText(getTuner().getPreferredName());/getTunerIdLabel().setText(getTuner().getPreferredName() + getUsbInfo());/g' ./src/main/java/io/github/dsheirer/source/tuner/rtl/r8x/R8xTunerEditor.java
sed -i 's/getTunerIdLabel().setText(getDiscoveredTuner().getId() + (hasTuner() ? " ID:" + getTuner().getUniqueID() : ""));/getTunerIdLabel().setText(getDiscoveredTuner().getId() + (hasTuner() ? " ID:" + getTuner().getUniqueID() : "") + getUsbInfo());/g' ./src/main/java/io/github/dsheirer/source/tuner/rtl/RTL2832UnknownTunerEditor.java
sed -i 's/getTunerIdLabel().setText(getTuner().getPreferredName());/getTunerIdLabel().setText(getTuner().getPreferredName() + getUsbInfo());/g' ./src/main/java/io/github/dsheirer/source/tuner/rtl/fc0013/FC0013TunerEditor.java
sed -i 's/getTunerIdLabel().setText(getTuner().getPreferredName());/getTunerIdLabel().setText(getTuner().getPreferredName() + getUsbInfo());/g' ./src/main/java/io/github/dsheirer/source/tuner/rtl/e4k/E4KTunerEditor.java
sed -i 's/getTunerIdLabel().setText(getTuner().getPreferredName());/getTunerIdLabel().setText(getTuner().getPreferredName() + getUsbInfo());/g' ./src/main/java/io/github/dsheirer/source/tuner/hydrasdr/HydraSdrTunerEditor.java
