/*
 * *****************************************************************************
 * Copyright (C) 2014-2026 Dennis Sheirer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 * ****************************************************************************
 */

package io.github.dsheirer.dsp.tone;

/**
 * Standardized two-tone sequential paging (TTSP) frequency pools and the analog-tolerance math used to compare a
 * measured tone against configured/known tones.
 *
 * <p>Public-safety paging consoles encode tones from standardized mathematical matrices (Motorola Quick Call II
 * "Reed" groups, GE Type 99, Plectron, etc.).  By the time a tone is generated by the console, carried over copper or
 * fiber to a transmitter, broadcast over narrow-band FM, and (on digital trunked systems) compressed by an
 * AMBE/IMBE vocoder optimized for speech rather than continuous sine waves, the frequency measured by the
 * sdrtrunk DSP is rarely mathematically perfect.  A Quick Call II hardware encoder already carries a recognized
 * tolerance of roughly &plusmn;1.5%, so a targeted 600.9&nbsp;Hz tone may be measured anywhere from ~592&nbsp;Hz to
 * ~610&nbsp;Hz.</p>
 *
 * <p>Two operations support robust, duplicate-free tone handling:</p>
 * <ul>
 *   <li>{@link #withinTolerance(double, double)} / {@link #toneSequencesMatch(double, double, double, double)} -
 *       compare a measured tone (or A/B pair) against a reference using the &plusmn;1.5% operational tolerance, so
 *       reconciliation against the active playlist and the tombstone exclusion list never demands a bit-perfect
 *       match.</li>
 *   <li>{@link #snap(double)} - round a measured tone to the nearest standardized matrix value when it is within
 *       tolerance, which keeps the configuration database from filling with marginally varying duplicates and gives
 *       the human reviewer clean, recognizable frequencies.</li>
 * </ul>
 */
public final class ToneStandards
{
    /** Standard Quick Call II hardware encoder frequency tolerance (&plusmn;1.5%). */
    public static final double TOLERANCE_PERCENT = 1.5;

    /**
     * Motorola Quick Call II "Reed" group tones (Hz).  These are the tones enumerated in the public-safety paging
     * reference for Groups 1-6; the pool is intentionally conservative - {@link #snap(double)} only ever moves a
     * measured tone onto one of these values when it is already within {@link #TOLERANCE_PERCENT} of it.
     */
    private static final double[] MOTOROLA_QCII = {
        349.0, 410.8, 510.5,    //Group 1
        600.9, 707.3, 879.0,    //Group 2
        288.5, 313.8, 1006.9,   //Group 3
        339.6, 399.8, 470.5,    //Group 4
        584.8, 688.3, 855.5,    //Group 5
        1151.4, 1357.6, 1598.0  //Group 6
    };

    /** GE Type 99 group tones (Hz) - groups A, B and C. */
    private static final double[] GE_TYPE_99 = {
        592.5, 607.5, 712.5
    };

    /** Plectron-style integer-cadence tones (Hz). */
    private static final double[] PLECTRON = {
        1200.0, 1400.0
    };

    /** Combined, de-duplicated pool used for snapping. */
    private static final double[] ALL_STANDARD_TONES = combine(MOTOROLA_QCII, GE_TYPE_99, PLECTRON);

    private ToneStandards()
    {
    }

    private static double[] combine(double[]... pools)
    {
        java.util.TreeSet<Double> set = new java.util.TreeSet<>();

        for(double[] pool : pools)
        {
            for(double tone : pool)
            {
                set.add(tone);
            }
        }

        double[] result = new double[set.size()];
        int i = 0;

        for(double tone : set)
        {
            result[i++] = tone;
        }

        return result;
    }

    /**
     * Indicates whether a measured tone matches a reference tone within the given percentage tolerance.
     *
     * @param reference known/configured tone frequency (Hz); a non-positive reference never matches
     * @param measured tone frequency measured by the DSP (Hz)
     * @param tolerancePercent allowable deviation as a percentage of the reference (e.g. 1.5 for &plusmn;1.5%)
     * @return true if the measured tone is within tolerance of the reference
     */
    public static boolean withinTolerance(double reference, double measured, double tolerancePercent)
    {
        if(reference <= 0)
        {
            return false;
        }

        double allowed = Math.abs(reference) * (tolerancePercent / 100.0);
        return Math.abs(reference - measured) <= allowed;
    }

    /**
     * Indicates whether a measured tone matches a reference tone within the standard &plusmn;1.5% tolerance.
     */
    public static boolean withinTolerance(double reference, double measured)
    {
        return withinTolerance(reference, measured, TOLERANCE_PERCENT);
    }

    /**
     * Indicates whether two A/B tone sequences are the same page within the standard tolerance.  Both the A tone and
     * the B tone must match.  A non-positive B tone on both sides is treated as a single-tone ("Long A"/All-Call)
     * page, in which case only the A tones are compared.
     *
     * @param a1 first sequence A tone (Hz)
     * @param b1 first sequence B tone (Hz), or &le;0 for a single-tone page
     * @param a2 second sequence A tone (Hz)
     * @param b2 second sequence B tone (Hz), or &le;0 for a single-tone page
     * @return true if the two sequences match within tolerance
     */
    public static boolean toneSequencesMatch(double a1, double b1, double a2, double b2)
    {
        if(!withinTolerance(a1, a2))
        {
            return false;
        }

        //Single-tone (Long A / All-Call) page on both sides - the A tones already matched.
        if(b1 <= 0 && b2 <= 0)
        {
            return true;
        }

        return withinTolerance(b1, b2);
    }

    /**
     * Snaps a measured tone to the nearest standardized matrix value when the measurement is within
     * {@link #TOLERANCE_PERCENT} of that value; otherwise returns the measurement rounded to one decimal place.
     * This intelligent frequency snapping prevents the database from filling with marginally varying duplicate
     * records and presents the human reviewer with clean, recognizable frequencies.
     *
     * @param measured tone frequency measured by the DSP (Hz)
     * @return the nearest standard tone, or the rounded measurement when no standard tone is within tolerance
     */
    public static double snap(double measured)
    {
        if(measured <= 0)
        {
            return measured;
        }

        double best = Double.NaN;
        double bestDelta = Double.MAX_VALUE;

        for(double standard : ALL_STANDARD_TONES)
        {
            double delta = Math.abs(standard - measured);

            if(delta < bestDelta && withinTolerance(standard, measured))
            {
                bestDelta = delta;
                best = standard;
            }
        }

        if(!Double.isNaN(best))
        {
            return best;
        }

        return Math.round(measured * 10.0) / 10.0;
    }
}
