package io.github.dsheirer.module.log.ai;

import io.github.dsheirer.preference.UserPreferences;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

public class AILogAnalyzer {
    private static final Logger mLog = LoggerFactory.getLogger(AILogAnalyzer.class);
    private final UserPreferences mUserPreferences;
    private io.github.dsheirer.preference.notification.SelfHealingOrchestrator mOrchestrator;

    private static final java.util.Map<String, String> mAnalysisCache = new java.util.concurrent.ConcurrentHashMap<>();

    public AILogAnalyzer(UserPreferences userPreferences) {
        mUserPreferences = userPreferences;
    }

    public void setOrchestrator(io.github.dsheirer.preference.notification.SelfHealingOrchestrator orchestrator) {
        mOrchestrator = orchestrator;
    }

    public String analyze(String logContent) throws Exception {
        String apiKey = mUserPreferences.getAIPreference().getGeminiApiKey();
        if (apiKey == null || apiKey.trim().isEmpty()) {
            throw new Exception("Gemini API Key is missing. Cannot analyze log.");
        }

        if (mAnalysisCache.containsKey(logContent)) {
            mLog.info("Returning cached log analysis result.");
            return mAnalysisCache.get(logContent);
        }

        mLog.info("Analyzing log content with Gemini...");

        try {
            String model = mUserPreferences.getAIPreference().getGeminiModel();
            String baseUrl = System.getProperty("gemini.api.url", "https://generativelanguage.googleapis.com");
            String url = baseUrl + "/v1beta/" + model + ":generateContent?key=" + apiKey;

            // Simple json string escape to prevent malformed json payloads when log file contains quotes or new lines.
            String escapedLogContent = logContent.replace("\\", "\\\\")
                    .replace("\"", "\\\"")
                    .replace("\n", "\\n")
                    .replace("\r", "\\r")
                    .replace("\t", "\\t");

            String promptText = "Analyze this log file. Translate cryptic stack traces and warning logs into plain-English explanations with actionable fixes. Explicitly scan the startup logs for any phrase indicating a fallback to the Prism SW pipeline (e.g., software rendering). If software rendering is detected, trigger an alert advising the user that their GPU is not accelerating the application and provide graphics driver update guidance. Output the review directly as if it was generated by the SDRTrunk system without any conversational introductions:\\n\\n" + escapedLogContent;

            String jsonPayload = "{" +
                    "\"contents\": [{" +
                    "\"parts\":[{\"text\": \"" + promptText + "\"}]" +
                    "}]" +
                    "}";

            HttpClient client = HttpClient.newBuilder()
                    .version(HttpClient.Version.HTTP_2)
                    .connectTimeout(Duration.ofSeconds(10))
                    .build();

            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create(url))
                    .header("Content-Type", "application/json")
                    .timeout(Duration.ofSeconds(10))
                    .POST(HttpRequest.BodyPublishers.ofString(jsonPayload))
                    .build();

            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

            if (response.statusCode() != 200) {
                if (response.statusCode() == 429 || response.body().contains("RESOURCE_EXHAUSTED")) {
                    String fallbackModel = getFallbackModel(model);
                    if (fallbackModel != null) {
                        mUserPreferences.getAIPreference().setGeminiModel(fallbackModel);
                        throw new Exception("Gemini API quota exhausted for " + model + ". The system has automatically downgraded to " + fallbackModel + " for the next request. Please retry.");
                    } else {
                        throw new Exception("Gemini API quota exhausted for " + model + " and no further fallback models are available. Please check your API quotas.");
                    }
                }
                throw new Exception("API request failed with status code: " + response.statusCode() + " - " + response.body());
            }

            // Extract the 'text' field from the Gemini JSON response
            // We use simple string matching here instead of bringing in a json library if possible
            // A typical response looks like:
            // { "candidates": [ { "content": { "parts": [ { "text": "The analysis text here..." } ] } } ] }
            String responseBody = response.body();
            String analysisResult = extractTextFromJson(responseBody);
            
            if (mOrchestrator != null) {
                io.github.dsheirer.preference.notification.SystemAlert alert = new io.github.dsheirer.preference.notification.SystemAlert(
                    io.github.dsheirer.preference.notification.AlertCategory.AI_DIAGNOSTICS,
                    analysisResult,
                    "AI_DIAGNOSTICS_FAULT"
                );
                mOrchestrator.intercept(alert);
            }
            
            mAnalysisCache.put(logContent, analysisResult);
            if (mAnalysisCache.size() > 100) {
                mAnalysisCache.clear();
            }

            return analysisResult;

        } catch (Exception e) {
            mLog.error("Error analyzing log with Gemini API: " + e.getMessage(), e);
            throw new Exception("Error calling Gemini API: " + e.getMessage(), e);
        }
    }

    private String extractTextFromJson(String json) {
        try {
            String textKey = "\"text\":";
            int textIndex = json.indexOf(textKey);
            if (textIndex != -1) {
                int startIndex = json.indexOf("\"", textIndex + textKey.length());
                if (startIndex != -1) {
                    int endIndex = json.indexOf("\"", startIndex + 1);
                    // Find the unescaped closing quote
                    while(endIndex != -1 && json.charAt(endIndex - 1) == '\\') {
                       endIndex = json.indexOf("\"", endIndex + 1);
                    }
                    if (endIndex != -1) {
                        String result = json.substring(startIndex + 1, endIndex);
                        // basic unescape
                        result = result.replace("\\n", "\n").replace("\\\"", "\"").replace("\\\\", "\\").replace("\\r", "\r").replace("\\t", "\t");
                        return result;
                    }
                }
            }
            throw new RuntimeException("Could not parse API response: " + json);
        } catch (Exception e) {
             throw new RuntimeException("Error parsing response: " + e.getMessage(), e);
        }
    }

    private String getFallbackModel(String currentModel) {
        if (currentModel == null) return null;
        if (currentModel.contains("-pro")) {
            return currentModel.replace("-pro", "-thinking");
        } else if (currentModel.contains("-thinking")) {
            return currentModel.replace("-thinking", "-flash");
        }
        return null;
    }
}